name: release-action
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{github.ref_name}}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            usabillabv/openapi3-validator:latest
            usabillabv/openapi3-validator:${{github.ref_name}}
